/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminIfteakar2026RouteImport } from './routes/admin-ifteakar-2026'
import { Route as IndexRouteImport } from './routes/index'

const AdminIfteakar2026Route = AdminIfteakar2026RouteImport.update({
  id: '/admin-ifteakar-2026',
  path: '/admin-ifteakar-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-ifteakar-2026': typeof AdminIfteakar2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-ifteakar-2026': typeof AdminIfteakar2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-ifteakar-2026': typeof AdminIfteakar2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin-ifteakar-2026'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin-ifteakar-2026'
  id: '__root__' | '/' | '/admin-ifteakar-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminIfteakar2026Route: typeof AdminIfteakar2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin-ifteakar-2026': {
      id: '/admin-ifteakar-2026'
      path: '/admin-ifteakar-2026'
      fullPath: '/admin-ifteakar-2026'
      preLoaderRoute: typeof AdminIfteakar2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminIfteakar2026Route: AdminIfteakar2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
